### ISSUE TITLE
Why do PACER tests keep barfing in Travis?

### ISSUE THREAD

**Issue by arderyp** [freelawproject/juriscraper#251] opened 2019-01-10 04:11 UTC
For the past few months, I push from my machine, where all tests pass, and inevitably the PACER tests barf in Travis.

**Comment by mlissner** [comment] 2019-01-10 20:36
This is a good question. Looks like:

```
======================================================================
ERROR: test_using_same_report_twice (tests.test_pacer.PacerDocketReportTest)
Do the caches get properly nuked between runs?
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/freelawproject/juriscraper/tests/test_pacer.py", line 723, in test_using_same_report_twice
    d = self.report.data.copy()
  File "/home/travis/build/freelawproject/juriscraper/juriscraper/pacer/docket_report.py", line 48, in data
    data = self.metadata.copy()
  File "/home/travis/build/freelawproject/juriscraper/juriscraper/pacer/docket_report.py", line 290, in metadata
    self._set_metadata_values()
  File "/home/travis/build/freelawproject/juriscraper/juriscraper/pacer/docket_report.py", line 949, in _set_metadata_values
    )[0]
IndexError: list index out of range
======================================================================
ERROR: test_ordering_by_date_filed (tests.test_pacer.PacerFreeOpinionsTest)
Can we change the ordering?
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/freelawproject/juriscraper/tests/test_pacer.py", line 321, in test_ordering_by_date_filed
    len(report.data),
  File "/home/travis/build/freelawproject/juriscraper/juriscraper/pacer/free_documents.py", line 98, in data
    'opinions reported")]')[0].tail)
IndexError: list index out of range
======================================================================
FAIL: test_queries (tests.test_pacer.PacerDocketReportTest)
Do a variety of queries work?
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/freelawproject/juriscraper/tests/test_pacer.py", line 679, in test_queries
    "date. Got %s." % row_count)
AssertionError: Didn't get expected number of rows when filtering by start date. Got -1.
```

I think I broke this somehow, though I don't know how. I suspect it works locally because of VCR cassettes you have. I'll see if I can dig into this, unless you have time to.

**Comment by arderyp** [comment] 2019-01-11 01:19
@mlissner, I think some PACER tests might get skipped when running tests on my machine, since I haven't configured PACER authentication.  However, I have seen instances recently where running tests will fail with some PACER error, then I will run the tests again immediately and they will pass.  So, it's inconsistent on my machine (maybe some of the tests hit the network?).  In Travis, however, the PACER tests seem to be failing consistently over the past 2 months or so.  One oddity in all of this, which is apparent if you look at our [commit log](https://github.com/freelawproject/juriscraper/commits/master), is that @umeboshi2's commits seem to pass Travis (green checks), but all of your commits and mine in the past two months or so have failed.  Maybe it has something to do with the fact that you are merging his changes via PR, whereas you and I commit directly to master?

**Comment by mlissner** [comment] 2019-01-11 01:30
I'm going to try to fix this tonight once the kids are in bed, so starting around 8:30. I just looked at it and I can't imagine why it fails on Travis but not locally. Gotta get to the bottom of it.

**Comment by mlissner** [comment] 2019-01-11 19:06
Well, I can't figure out what the heck is happening here. For some reason when these tests run, they automatic login feature doesn't seem to be working. I am dialed in on the first test failure, `test_using_same_report_twice`, which fails because an XPath doesn't work. Usually that's because of one of two things. Either:

1. The HTML its parsing isn't the page we expect it to be, or
2. The XPath is no good and needs to be refined.

I wanted to know which, so I made a build that printed the HTML when the failure happened:

https://travis-ci.org/freelawproject/juriscraper/builds/478204909

The HTML is jumbled a bit for reason I don't understand, but you can see that it's from a login page. That's weird because it should be a docket, and when login pages are encountered instead, the system is supposed to automatically log in. 

I'm going to do a build where it manually logs in, but it seems unnecessary and it bothers me that something isn't right here that I can't pin down.

**Comment by mlissner** [comment] 2019-01-11 22:31
Well, I've wasted a lot of time on this now and I don't know why Travis fails and our local builds work fine. I just know it's super frustrating. The latest things I've tried:

 - I've removed vcr from the entire project. Having used it for a while now, I can't stand the uncertainty it brings and it makes me suspect that it is somehow involved.
 - I just deleted the caches that Travis maintains. I think these are just a cache of what's in pip, but my dependencies are the same as those on Travis, my code is the same, and my outcomes are totally different. Maybe it's the cache. 

I'm completely out of time and I'm pretty much out of ideas.

**Comment by arderyp** [comment] 2019-01-12 01:16
Yikes, this sounds like a nightmare.  Is there no way to debug Travis other than pushing changes to master?

**Comment by mlissner** [comment] 2019-01-12 01:19
Yeah, I've lost my day and my mind is in hot pursuit. I don't know of any other way to test travis, nope — I suppose I could/should do this in a branch. 

At this point, I've taken the failing test and pulled it out so that it's the only thing that runs. It's particularly weird though. Test A works when in total isolation. When I add the other failing test (test B), then both fail. If I remove test A, test B continues failing even in isolation.

My current theory is that it's a timing thing. If you hit the server too fast it blocks you or something. That'd explain why it's travis and not local and it'd explain why the tests interact. I've added some waits to the program and I'm testing that now. Maybe?

**Comment by mlissner** [comment] 2019-01-12 01:20
Nope.

**Comment by arderyp** [comment] 2019-01-12 01:43
Hmm, and we have no clues as to why test B is failing, since its the one consistent piece?

**Comment by mlissner** [comment] 2019-01-12 01:44
Nope. Can't figure out how to make it fail locally. Only thing I see is that for some reason when we try to query a docket report, we aren't logged in, even though a moment ago we were.

**Comment by mlissner** [comment] 2019-01-12 01:44
I'm trying to set up circleci now to see if I can reproduce the same error there. If so, that'll help. If not, we ditch Travis.

**Comment by arderyp** [comment] 2019-01-12 01:45
also, we don't think this is due to some Travis config or test logic change that we made, right?  Instead we think its due to some change on the PACER side of things?

**Comment by arderyp** [comment] 2019-01-12 01:45
could the Travis machine be blocked by PACER, causing network/auth failures?

**Comment by mlissner** [comment] 2019-01-12 01:46
I think Travis is doing something weird and I have no idea what. Circle works: https://circleci.com/gh/freelawproject/juriscraper/4 !!!

The WTF on this one is pretty through the roof. 

> could the Travis machine be blocked by PACER, causing network/auth failures?

I considered that, but lots of the requests to PACER do work from Travis.

**Comment by arderyp** [comment] 2019-01-12 01:49
I wouldn't be entirely surprised if something was up at Travis.  I am not longer getting build reports from them, and (according to their support) you aren't either.  Have you been getting failure email reports during all of your pushes today?  Might be totally unrelated, but it seems something is up over there.

**Comment by mlissner** [comment] 2019-01-12 01:51
I'm not getting failure reports, but I don't know if I have them configured or if they're auto-filtered to my inbox trash or something, so I'm not a useful metric on that one. 

I'm doing a full build on circle now and we'll see if it passes. If so, there's a lot of optimization to do in their build config (caching dependencies, doing deployment like we do with travis, etc.) I don't think I'll have time tonight to get that done, so we probably need a fresh bug to work on that. You have any interest? I've been impressed with Circle so far. Seems like good competition (and thank god for it).

**Comment by arderyp** [comment] 2019-01-12 01:53
I have them enabled and used to get them but they are being suppressed somehow.  Travis support noted this themselves when they inspected their logs.

"we probably need a fresh bug to work on that. You have any interest?"

Maybe, though I am not entirely sure I understand what you are saying.

**Comment by mlissner** [comment] 2019-01-12 01:57
Sorry, I'm feeling a bit crazy trying to get this fixed, so I should slow down and communicate better. Here's the state of things:

https://circleci.com/gh/freelawproject/juriscraper/5

71 tests, all of them passing, thank goodness! 

The next step is to take the circle config and improve it so that it caches dependencies between runs, stores results, pushes new versions to pypi, posts to Slack etc. 

There's a handful of good stuff you can do with circle to configure it properly and I didn't do any of it while I was trying to get this fixed. I think this would just mean going through the circleci documentation and figuring it all out, essentially.

**Comment by arderyp** [comment] 2019-01-12 03:16
Oh, okay.  Well, I'm glad everything is working on Circle!  I'm unfamiliar with it, but can try to poke through the documentation when I get a chance.  Maybe I will have some free time Sunday, but this weekend is generally kind pretty busy.  Sorry to send you down this hellish rabbit hole last night/today :confused:

**Comment by mlissner** [comment] 2019-01-14 17:49
No need to apologize. I appreciate you prompting me to work on it. I think we can close this and move to the other issue. Feel free to reopen if you think there's more here.

**Closed by mlissner** 2019-01-14 17:49 UTC
